.\" Manpage for chemps2 executable
.\" Contact sebastianwouters [at] gmail.com
.TH CHEMPS2 1 "24 August 2015" "version 1.6" "chemps2 v1.6"

.SH NAME
chemps2 \- spin-adapted DMRG for ab initio quantum chemistry

.SH SYNOPSIS
.B chemps2
.RI "[" "OPTION" "]"
.RI "..."

.SH DESCRIPTION
\fBchemps2\fR is a scientific code to perform spin-adapted density matrix renormalization group (DMRG) calculations for ab initio quantum chemistry fcidump files. This method allows one to obtain numerical accuracy in active spaces beyond the capabilities of full configuration interaction (FCI) and can return the active space 2-RDM. The method is therefore ideal to replace the FCI solver in the complete active space configuration interaction (CASCI) and complete active space self consistent field (CASSCF) methods. The link to the user manual can be found in the section \fBSEE ALSO\fR.

.SH OPTIONS
.SS SYMMETRY
Conventions for the symmetry group and irrep numbers (same as psi4):
.PP
.EX
                 |  0    1    2    3    4    5    6    7   
        ---------|-----------------------------------------
        0 : c1   |  A                                      
        1 : ci   |  Ag   Au                                
        2 : c2   |  A    B                                 
        3 : cs   |  Ap   App                               
        4 : d2   |  A    B1   B2   B3                      
        5 : c2v  |  A1   A2   B1   B2                      
        6 : c2h  |  Ag   Bg   Au   Bu                      
        7 : d2h  |  Ag   B1g  B2g  B3g  Au   B1u  B2u  B3u 
.EE
.SS ARGUMENTS
.TP
.BR "\-f" ", " "\-\-fcidump=\fIfilename\fB"
Set the fcidump filename. Note that orbital irreps in this file follow molpro convention!
.TP
.BR "\-g" ", " "\-\-group=\fIint\fB"
Set the psi4 symmetry group number [\fI0-7\fR] which corresponds to the fcidump file.
.TP
.BR "\-m" ", " "\-\-multiplicity=\fIint\fB"
Overwrite the spin multiplicity [\fI2S+1\fR] of the fcidump file.
.TP
.BR "\-n" ", " "\-\-nelectrons=\fIint\fB"
Overwrite the number of electrons of the fcidump file.
.TP
.BR "\-i" ", " "\-\-irrep=\fIint\fB"
Overwrite the target wavefunction irrep [\fI0-7\fR] of the fcidump file (psi4 convention).
.TP
.BR "\-D" ", " "\-\-sweep_d=\fIint,int,int\fB"
Set the bond dimensions for the successive sweep instructions (positive integers).
.TP
.BR "\-E" ", " "\-\-sweep_econv=\fIflt,flt,flt\fB"
Set the energy convergence to stop sweep instructions (positive floats).
.TP
.BR "\-M" ", " "\-\-sweep_maxit=\fIint,int,int\fB"
Set the maximum number of sweeps for the sweep instructions (positive integers).
.TP
.BR "\-N" ", " "\-\-sweep_noise=\fIflt,flt,flt\fB"
Set the noise prefactors for the successive sweep instructions (floats).
.TP
.BR "\-e" ", " "\-\-excitation=\fIint\fB"
Set which excitation should be calculated (positive integer). If not set, the ground state is calculated.
.TP
.BR "\-o" ", " "\-\-twodmfile=\fIfilename\fB"
Set the filename to dump the 2-RDM. If not set, the 2-RDM is not dumped.
.TP
.BR "\-c" ", " "\-\-checkpoint"
Read and create MPS checkpoints.
.TP
.BR "\-p" ", " "\-\-print_corr"
Print correlation functions.
.TP
.BR "\-t" ", " "\-\-tmpfolder=\fIpath\fB"
Overwrite the tmp folder for the renormalized operators (default \fI/tmp\fR).
.TP
.BR "\-r" ", " "\-\-reorder=\fIint,int,int\fB"
Specify an orbital reordering w.r.t. the fcidump file (counting starts at 0).
.TP
.BR "\-h" ", " "\-\-help"
Display this help.
.SS EXAMPLE
.PP
.EX
 $ cd /tmp
 $ wget 'https://github.com/SebWouters/CheMPS2/raw/master/tests/matrixelements/H2O.631G.FCIDUMP'
 $ ls \-al H2O.631G.FCIDUMP
 $ chemps2 \-\-fcidump=H2O.631G.FCIDUMP \\
           \-\-group=5 \\
           \-\-sweep_d=200,1000 \\
           \-\-sweep_econv=1e-8,1e-8 \\
           \-\-sweep_maxit=2,10 \\
           \-\-sweep_noise=0.05,0.0 \\
           \-\-twodmfile=2dm.out \\
           \-\-print_corr \\
           \-\-reorder=6,5,4,3,2,1,0,7,8,9,10,11,12
.EE

.SH AUTHOR
Written by
Sebastian Wouters <\&\%sebastianwouters@gmail\&.com\&>

.SH BUGS
Reporting bugs:
\fI\%https://github.com/sebwouters/CheMPS2/issues\fR

.SH SEE ALSO
User manual:
\fI\%http://sebwouters.github.io/CheMPS2/index.html\fR

.SH COPYRIGHT
.EX
CheMPS2: a spin-adapted implementation of DMRG for ab initio quantum chemistry
Copyright (C) 2013-2015 Sebastian Wouters

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.EE

